"""Adapter protocols for Hermes-to-Alpha Harness integration.

Three protocols that the Hermes runtime implements to plug into the
research loop. Stub implementations in stubs.py allow testing without
Hermes installed. See __init__.py for the full ownership contract.
"""

from __future__ import annotations

from typing import Protocol

from alpha_harness.hermes_boundary.contracts import (
    MemoryContext,
    ResearchCycleRequest,
    ResearchCycleResponse,
)
from alpha_harness.schemas.memory import MemoryEntry

# ── Adapter protocols ────────────────────────────────────────────────────────


class AgentRuntimeAdapter(Protocol):
    """Translates between Hermes agent actions and Alpha Harness cycles.

    The Hermes runtime implements this protocol.  A typical flow:

        1. Agent produces a hypothesis (natural language).
        2. Hermes adapter calls ``translate_to_request()`` to build a typed
           ResearchCycleRequest.
        3. Harness orchestrator runs the cycle.
        4. Adapter calls ``translate_to_response()`` to build a simplified
           ResearchCycleResponse for the agent's context window.
        5. Agent reads the response and decides next action.

    What Hermes must provide:
        - Parse agent output to extract hypothesis text and rationale.
        - Map agent intent to CycleGoal (explore / refine / audit).
        - Feed the response back into the agent's conversation.

    What Alpha Harness guarantees:
        - The ResearchCycleRequest schema is stable across minor versions.
        - The orchestrator will always return a valid ExperimentRecord.
        - Evaluation is deterministic and reproducible.
    """

    def translate_to_request(self, agent_output: str) -> ResearchCycleRequest:
        """Parse raw agent output into a typed research cycle request."""
        ...

    def translate_to_response(self, experiment_id: str) -> ResearchCycleResponse:
        """Build an agent-friendly response from a completed experiment."""
        ...


class MemoryProviderAdapter(Protocol):
    """Bridge between Alpha Harness memory and Hermes memory/RAG systems.

    Allows Hermes to store and retrieve research memory without knowing
    the internal schema.  The adapter handles format conversion.

    What Hermes must provide:
        - A storage backend (vector DB, file store, or in-memory).
        - Retrieval by semantic similarity or tags.

    What Alpha Harness guarantees:
        - MemoryEntry objects are self-contained and serialisable.
        - Memory categories are a stable enum.
        - Memory is append-only (no silent mutations).
    """

    def store(self, entry: MemoryEntry) -> str:
        """Persist a memory entry. Returns the stored entry id."""
        ...

    def retrieve_by_tags(self, tags: list[str], limit: int = 10) -> list[MemoryEntry]:
        """Retrieve memory entries matching any of the given tags."""
        ...

    def retrieve_recent(self, limit: int = 10) -> list[MemoryEntry]:
        """Retrieve the most recent memory entries."""
        ...


class ContextInjectionAdapter(Protocol):
    """Builds research context for injection into the Hermes agent prompt.

    This adapter controls what the LLM sees about past research. It
    queries harness registries and memory, then packs relevant information
    into a MemoryContext that the Hermes prompt assembler can use.

    What Hermes must provide:
        - A prompt assembler that accepts MemoryContext and renders it
          into a system message section.
        - A token budget so the adapter knows how much context to pack.

    What Alpha Harness guarantees:
        - MemoryContext is a flat, serialisable structure.
        - The adapter respects the token budget (approximate).
        - No evaluation internals leak into the context — only summaries.

    What remains deterministic (outside the LLM loop):
        - Memory selection criteria (category, recency, relevance).
        - Experiment summaries (factual, not generated by LLM).
        - Counts and statistics (promoted factors, total experiments).
    """

    def build_context(self, token_budget: int = 2000) -> MemoryContext:
        """Build a token-budgeted research context snapshot."""
        ...
